// <auto-generated />
using System;
using CustomerReturnCRM.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomerReturnCRM.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260914100000_AddBaleIntegration")]
    partial class AddBaleIntegration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("CustomerReturnCRM.Domain.Entities.BaleConnectToken", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedNever().HasColumnType("uniqueidentifier");
                b.Property<Guid>("BusinessId").HasColumnType("uniqueidentifier");
                b.Property<Guid>("CustomerId").HasColumnType("uniqueidentifier");
                b.Property<string>("TokenHash").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<DateTime>("ExpiresAtUtc").HasColumnType("datetime2");
                b.Property<DateTime?>("UsedAtUtc").HasColumnType("datetime2");
                b.Property<bool>("IsRevoked").HasColumnType("bit");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("BusinessId");
                b.HasIndex("CustomerId");
                b.ToTable("BaleConnectTokens");
            });

            modelBuilder.Entity("CustomerReturnCRM.Domain.Entities.BaleCustomerIdentity", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedNever().HasColumnType("uniqueidentifier");
                b.Property<Guid>("BusinessId").HasColumnType("uniqueidentifier");
                b.Property<Guid>("CustomerId").HasColumnType("uniqueidentifier");
                b.Property<long>("BaleUserId").HasColumnType("bigint");
                b.Property<long>("BaleChatId").HasColumnType("bigint");
                b.Property<string>("Username").HasColumnType("nvarchar(max)");
                b.Property<DateTime>("ConnectedAtUtc").HasColumnType("datetime2");
                b.Property<DateTime?>("LastSeenAtUtc").HasColumnType("datetime2");
                b.Property<bool>("IsActive").HasColumnType("bit");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("BusinessId");
                b.HasIndex("CustomerId");
                b.ToTable("BaleCustomerIdentities");
            });

            modelBuilder.Entity("CustomerReturnCRM.Domain.Entities.BaleConnectToken", b =>
            {
                b.HasOne("CustomerReturnCRM.Domain.Entities.Business", "Business")
                    .WithMany()
                    .HasForeignKey("BusinessId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.HasOne("CustomerReturnCRM.Domain.Entities.Customer", "Customer")
                    .WithMany("BaleConnectTokens")
                    .HasForeignKey("CustomerId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.Navigation("Business");
                b.Navigation("Customer");
            });

            modelBuilder.Entity("CustomerReturnCRM.Domain.Entities.BaleCustomerIdentity", b =>
            {
                b.HasOne("CustomerReturnCRM.Domain.Entities.Business", "Business")
                    .WithMany()
                    .HasForeignKey("BusinessId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.HasOne("CustomerReturnCRM.Domain.Entities.Customer", "Customer")
                    .WithMany("BaleIdentities")
                    .HasForeignKey("CustomerId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.Navigation("Business");
                b.Navigation("Customer");
            });

            modelBuilder.Entity("CustomerReturnCRM.Domain.Entities.Customer", b =>
            {
                b.Navigation("BaleIdentities");
                b.Navigation("BaleConnectTokens");
            });
        }
    }
}
