services:

  migration:
    image: ghcr.io/mohamadrahmani/customerreturncrm-migration:${IMAGE_TAG:-latest}
    container_name: customerreturncrm-migration
    environment:
      ConnectionStrings__DefaultConnection: "Server=185.8.174.94,1433;Database=CustomerReturnCRM;User Id=BmsDbUser;Password=${DB_PASSWORD};TrustServerCertificate=True;Connection Timeout=30;"

  api:
    image: ghcr.io/mohamadrahmani/customerreturncrm-api:${IMAGE_TAG:-latest}
    container_name: customerreturncrm-api
    environment:
      ConnectionStrings__DefaultConnection: "Server=185.8.174.94,1433;Database=CustomerReturnCRM;User Id=BmsDbUser;Password=${DB_PASSWORD};TrustServerCertificate=True;Connection Timeout=30;"
      Jwt__Key: "${JWT_KEY}"
      Sms__Provider: "SmsIr"
      SMSApiKey: "${SMSApiKey}"
      SMSLineNumber: "${SMSLineNumber}"
    ports:
      - "127.0.0.1:8080:8080"

  web:
    image: ghcr.io/mohamadrahmani/customerreturncrm-web:${IMAGE_TAG:-latest}
    container_name: customerreturncrm-web
    environment:
      NEXT_PUBLIC_API_BASE_URL: "/api"
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - api
