"use client";

import { useMemo, useState, type ReactNode } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useAuth } from "@/components/auth-provider";
import { apiFetch } from "@/lib/api";
import { gregorianToJalali, jalaliMonthDays, jalaliMonthNames, jalaliToIso, shiftJalaliMonth, todayJalali, type JalaliDate } from "@/lib/jalali";

type Customer={id:string;firstName:string;lastName:string|null;mobile:string};
type Service={id:string;title:string;defaultPrice:number;defaultDurationMinutes:number;isActive:boolean};
type Staff={id:string;firstName:string;lastName:string;isActive:boolean};
type AppointmentService={id:string;serviceId:string;staffId:string;serviceTitle:string;price:number;durationMinutes:number};
type Appointment={id:string;customerId:string;startAt:string;endAt:string;status:number;note:string|null;services:AppointmentService[]};
type Page<T>={items:T[];page:number;pageSize:number;totalCount:number;totalPages:number};
type Form={customerId:string;serviceId:string;staffId:string;date:string;start:string;end:string;note:string};

const faNumber=new Intl.NumberFormat("fa-IR");
const faDate=new Intl.DateTimeFormat("fa-IR-u-ca-persian",{weekday:"long",day:"numeric",month:"long",year:"numeric"});
const weekDays=["ش","ی","د","س","چ","پ","ج"];
function isoDate(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function parseIso(v:string){const [y,m,d]=v.split("-").map(Number);return new Date(y,m-1,d)}
function shiftDate(v:string,n:number){const d=parseIso(v);d.setDate(d.getDate()+n);return isoDate(d)}
function localDateTime(d:string,t:string){return `${d}T${t}:00`}
function addMinutes(t:string,n:number){const [h,m]=t.split(":").map(Number);const x=h*60+m+n;return `${String(Math.floor(x/60)%24).padStart(2,"0")}:${String(x%60).padStart(2,"0")}`}
function customerName(c?:Customer){return c?[c.firstName,c.lastName].filter(Boolean).join(" "):"مشتری"}
function staffName(s?:Staff){return s?[s.firstName,s.lastName].filter(Boolean).join(" "):"بدون کارکنان"}
function timeOf(v:string){return new Date(v).toLocaleTimeString("fa-IR",{hour:"2-digit",minute:"2-digit"})}
function statusLabel(s:number){return s===0?"در انتظار تأیید":s===1?"تأیید شده":s===2?"تکمیل شده":s===3?"لغو شده":"عدم مراجعه"}
function statusClass(s:number){return s===1?"border-indigo-200 bg-indigo-50 text-indigo-700":s===2?"border-emerald-200 bg-emerald-50 text-emerald-700":s===3?"border-slate-200 bg-slate-100 text-slate-500":s===4?"border-rose-200 bg-rose-50 text-rose-700":"border-amber-200 bg-amber-50 text-amber-700"}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="block"><span className="mb-1.5 block text-xs font-bold text-slate-700">{label}</span>{children}</label>}

function JalaliDatePicker({value,onChange}:{value:string;onChange:(v:string)=>void}){
 const [open,setOpen]=useState(false);const current=parseIso(value);const selected=gregorianToJalali(current.getFullYear(),current.getMonth()+1,current.getDate());const [month,setMonth]=useState<JalaliDate>(selected);const first=parseIso(jalaliToIso({year:month.year,month:month.month,day:1}));const offset=(first.getDay()+1)%7;const days=jalaliMonthDays(month.year,month.month);const today=todayJalali();const cells=Array.from({length:offset+days},(_,i)=>i<offset?null:i-offset+1);
 return <div className="relative"><button type="button" onClick={()=>setOpen(x=>!x)} className="crm-input flex w-full items-center justify-between"><span>{new Intl.DateTimeFormat("fa-IR-u-ca-persian",{day:"numeric",month:"long",year:"numeric"}).format(current)}</span><span>▦</span></button>{open&&<><button type="button" aria-label="بستن تقویم" className="fixed inset-0 z-30" onClick={()=>setOpen(false)}/><div className="absolute right-0 top-full z-40 mt-2 w-[320px] rounded-2xl border bg-white p-3 shadow-2xl"><div className="mb-3 flex items-center justify-between"><button type="button" onClick={()=>setMonth(m=>shiftJalaliMonth(m,-1))}>‹</button><b>{jalaliMonthNames[month.month-1]} {faNumber.format(month.year)}</b><button type="button" onClick={()=>setMonth(m=>shiftJalaliMonth(m,1))}>›</button></div><div className="mb-1 grid grid-cols-7 text-center text-[10px] font-bold text-slate-400">{weekDays.map(x=><span key={x}>{x}</span>)}</div><div className="grid grid-cols-7 gap-1">{cells.map((day,i)=>day===null?<span key={i}/>:<button type="button" key={day} onClick={()=>{onChange(jalaliToIso({year:month.year,month:month.month,day}));setOpen(false)}} className={`h-9 rounded-lg text-xs font-bold ${day===selected.day&&month.month===selected.month&&month.year===selected.year?"bg-pink-500 text-white":"hover:bg-slate-100"}`}>{faNumber.format(day)}</button>)}</div><button type="button" onClick={()=>{onChange(jalaliToIso(today));setMonth(today);setOpen(false)}} className="mt-3 w-full rounded-xl bg-slate-50 py-2 text-xs font-bold text-pink-600">امروز</button></div></>}</div>
}

function CustomerPicker({items,value,onChange}:{items:Customer[];value:string;onChange:(id:string)=>void}){
 const [open,setOpen]=useState(false);const [q,setQ]=useState("");const selected=items.find(x=>x.id===value);const filtered=items.filter(x=>`${x.firstName} ${x.lastName??""} ${x.mobile}`.includes(q.trim()));
 return <div className="relative"><button type="button" onClick={()=>setOpen(x=>!x)} className="crm-input flex w-full items-center justify-between"><span className={selected?"text-slate-900":"text-slate-400"}>{selected?customerName(selected):"انتخاب مشتری"}</span><span>⌄</span></button>{open&&<><button type="button" aria-label="بستن" className="fixed inset-0 z-30" onClick={()=>setOpen(false)}/><div className="absolute right-0 top-full z-40 mt-2 w-full overflow-hidden rounded-2xl border bg-white shadow-2xl"><div className="border-b p-2"><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="جستجوی نام، نام خانوادگی یا موبایل..." className="crm-input w-full"/></div><div className="max-h-64 overflow-y-auto p-1">{filtered.length===0?<div className="p-5 text-center text-xs text-slate-400">مشتری‌ای پیدا نشد.</div>:filtered.map(c=><button type="button" key={c.id} onClick={()=>{onChange(c.id);setQ("");setOpen(false)}} className="flex w-full items-center justify-between rounded-xl px-3 py-2.5 text-right hover:bg-pink-50"><span><span className="block text-sm font-bold">{customerName(c)}</span><span dir="ltr" className="block text-[11px] text-slate-400">{c.mobile}</span></span><span>›</span></button>)}</div></div></>}</div>
}

export default function AppointmentsPage(){
 const {auth,businessId,isReady}=useAuth();const activeBusinessId=businessId??auth?.businesses[0]?.id??null;const queryClient=useQueryClient();const today=isoDate(new Date());
 const [selectedDate,setSelectedDate]=useState(today);const [view,setView]=useState<"day"|"week">("week");const [staffFilter,setStaffFilter]=useState("all");const [modal,setModal]=useState<"create"|"detail"|null>(null);const [selected,setSelected]=useState<Appointment|null>(null);const [form,setForm]=useState<Form>({customerId:"",serviceId:"",staffId:"",date:today,start:"10:00",end:"11:00",note:""});const [saving,setSaving]=useState(false);const [error,setError]=useState("");
 const d=parseIso(selectedDate);const ws=new Date(d);ws.setDate(ws.getDate()-((ws.getDay()+1)%7));const start=view==="week"?isoDate(ws):selectedDate;const end=shiftDate(start,view==="week"?7:1);const dates=Array.from({length:view==="week"?7:1},(_,i)=>shiftDate(start,i));
 const appointments=useQuery({queryKey:["appointments",activeBusinessId,start,end],queryFn:()=>apiFetch<Page<Appointment>>(`/api/businesses/${activeBusinessId}/appointments?from=${encodeURIComponent(localDateTime(start,"00:00"))}&to=${encodeURIComponent(localDateTime(end,"00:00"))}&page=1&pageSize=200`),enabled:isReady&&!!activeBusinessId});
 const customers=useQuery({queryKey:["appointment-customers",activeBusinessId],queryFn:()=>apiFetch<Page<Customer>>(`/api/businesses/${activeBusinessId}/customers?page=1&pageSize=100&isActive=true`),enabled:isReady&&!!activeBusinessId});
 const services=useQuery({queryKey:["appointment-services",activeBusinessId],queryFn:()=>apiFetch<Page<Service>>(`/api/businesses/${activeBusinessId}/services?page=1&pageSize=100&isActive=true`),enabled:isReady&&!!activeBusinessId});
 const staff=useQuery({queryKey:["appointment-staff",activeBusinessId],queryFn:()=>apiFetch<Page<Staff>>(`/api/businesses/${activeBusinessId}/staff?page=1&pageSize=100&isActive=true`),enabled:isReady&&!!activeBusinessId});
 const customerMap=useMemo(()=>new Map((customers.data?.items??[]).map(x=>[x.id,x])),[customers.data]);const staffMap=useMemo(()=>new Map((staff.data?.items??[]).map(x=>[x.id,x])),[staff.data]);const visible=(appointments.data?.items??[]).filter(a=>staffFilter==="all"||a.services.some(s=>s.staffId===staffFilter));
 if(!isReady||!activeBusinessId)return <main className="p-4"><div className="h-32 animate-pulse rounded-3xl bg-white/70"/></main>;
 function openCreate(date=selectedDate,time="10:00"){setError("");setForm({customerId:"",serviceId:"",staffId:"",date,start:time,end:addMinutes(time,60),note:""});setModal("create")}
 async function create(){const service=services.data?.items.find(x=>x.id===form.serviceId);if(!form.customerId||!service||!form.staffId){setError("مشتری، خدمت و کارکنان را انتخاب کنید.");return}if(form.end<=form.start){setError("زمان پایان باید بعد از زمان شروع باشد.");return}setSaving(true);try{await apiFetch(`/api/businesses/${activeBusinessId}/appointments`,{method:"POST",body:JSON.stringify({customerId:form.customerId,startAt:localDateTime(form.date,form.start),endAt:localDateTime(form.date,form.end),note:form.note.trim()||undefined,services:[{serviceId:service.id,staffId:form.staffId}]})});setModal(null);await queryClient.invalidateQueries({queryKey:["appointments",activeBusinessId]})}catch(e){setError(e instanceof Error?e.message:"ثبت نوبت انجام نشد.")}finally{setSaving(false)}}
 async function action(kind:"confirm"|"cancel"){if(!selected)return;setSaving(true);setError("");try{await apiFetch(`/api/businesses/${activeBusinessId}/appointments/${selected.id}/${kind}`,{method:"POST"});setModal(null);await queryClient.invalidateQueries({queryKey:["appointments",activeBusinessId,start,end]})}catch(e){setError(e instanceof Error?e.message:"عملیات انجام نشد.")}finally{setSaving(false)}}
 return <main className="-mx-4 -mt-5 min-h-[calc(100vh-65px)] bg-gradient-to-b from-rose-50 via-pink-50/60 to-violet-50/40 px-4 pb-10 pt-5 sm:-mx-8 sm:-mt-8 sm:px-8 sm:pt-7"><div className="mx-auto max-w-7xl"><header className="mb-5 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[11px] font-bold text-pink-600">مدیریت زمان</p><h1 className="mt-1 text-2xl font-black">نوبت‌ها</h1><p className="mt-1 text-xs text-slate-500">تقویم روزانه و هفتگی نوبت‌ها</p></div><button type="button" onClick={()=>openCreate()} className="crm-action self-start">＋ نوبت جدید</button></header>
 <section className="crm-card mb-4 p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-2"><button type="button" onClick={()=>setSelectedDate(shiftDate(selectedDate,view==="week"?-7:-1))} className="crm-secondary-action">‹</button><button type="button" onClick={()=>setSelectedDate(today)} className="crm-secondary-action text-xs">امروز</button><button type="button" onClick={()=>setSelectedDate(shiftDate(selectedDate,view==="week"?7:1))} className="crm-secondary-action">›</button><b className="mr-2 text-sm">{faDate.format(parseIso(selectedDate))}</b></div><div className="flex flex-wrap gap-2"><select value={staffFilter} onChange={e=>setStaffFilter(e.target.value)} className="crm-input text-xs"><option value="all">همه کارکنان</option>{(staff.data?.items??[]).map(s=><option key={s.id} value={s.id}>{staffName(s)}</option>)}</select><div className="grid grid-cols-2 rounded-xl bg-slate-100 p-1"><button type="button" onClick={()=>setView("day")} className={`rounded-lg px-4 py-2 text-xs font-bold ${view==="day"?"bg-white text-pink-600 shadow":"text-slate-500"}`}>روزانه</button><button type="button" onClick={()=>setView("week")} className={`rounded-lg px-4 py-2 text-xs font-bold ${view==="week"?"bg-white text-pink-600 shadow":"text-slate-500"}`}>هفتگی</button></div></div></div></section>
 {appointments.isLoading?<div className="h-96 animate-pulse rounded-3xl bg-white/70"/>:<section className="overflow-x-auto rounded-3xl border bg-white"><div className={`min-w-[760px] grid ${view==="week"?"grid-cols-[64px_repeat(7,minmax(110px,1fr))]":"grid-cols-[64px_minmax(500px,1fr)]"}`}><div className="border-b bg-slate-50"/>{dates.map(x=><button type="button" key={x} onClick={()=>setSelectedDate(x)} className="border-b bg-slate-50 p-3 text-center text-xs font-bold hover:bg-pink-50">{faDate.format(parseIso(x))}</button>)}{Array.from({length:12},(_,i)=>i+9).map(hour=><div key={hour} className="contents"><div className="border-b border-l bg-slate-50 p-2 text-center text-[10px] text-slate-400">{faNumber.format(hour)}:۰۰</div>{dates.map(date=><div key={`${date}-${hour}`} className="min-h-[92px] border-b p-1.5 align-top">{visible.filter(a=>isoDate(new Date(a.startAt))===date&&new Date(a.startAt).getHours()===hour).map(a=><button type="button" key={a.id} onClick={()=>{setSelected(a);setError("");setModal("detail")}} className={`mb-1 w-full rounded-xl border p-2 text-right shadow-sm ${statusClass(a.status)}`}><span className="block text-[11px] font-black">{timeOf(a.startAt)} - {timeOf(a.endAt)}</span><span className="mt-1 block truncate text-xs font-bold">{customerName(customerMap.get(a.customerId))}</span><span className="mt-1 block truncate text-[10px]">{a.services.map(s=>`${s.serviceTitle} • ${staffName(staffMap.get(s.staffId))}`).join("، ")}</span><span className="mt-1 inline-block rounded-full bg-white/70 px-2 py-0.5 text-[9px] font-bold">{statusLabel(a.status)}</span></button>)}</div>)}</div>)}</div></section>}
 {modal==="create"&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4"><div className="w-full max-w-lg rounded-3xl bg-white p-5 shadow-2xl"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-lg font-black">ثبت نوبت جدید</h2><p className="text-xs text-slate-400">اطلاعات نوبت و کارکنان را وارد کنید.</p></div><button type="button" onClick={()=>setModal(null)}>✕</button></div><div className="grid gap-4 sm:grid-cols-2"><Field label="مشتری"><CustomerPicker items={customers.data?.items??[]} value={form.customerId} onChange={customerId=>setForm(f=>({...f,customerId}))}/></Field><Field label="خدمت"><select value={form.serviceId} onChange={e=>{const s=services.data?.items.find(x=>x.id===e.target.value);setForm(f=>({...f,serviceId:e.target.value,end:s?addMinutes(f.start,s.defaultDurationMinutes):f.end}))}} className="crm-input w-full"><option value="">انتخاب خدمت</option>{(services.data?.items??[]).map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></Field><Field label="کارکنان"><select value={form.staffId} onChange={e=>setForm(f=>({...f,staffId:e.target.value}))} className="crm-input w-full"><option value="">انتخاب کارکنان</option>{(staff.data?.items??[]).map(s=><option key={s.id} value={s.id}>{staffName(s)}</option>)}</select></Field><Field label="تاریخ"><JalaliDatePicker value={form.date} onChange={date=>setForm(f=>({...f,date}))}/></Field><Field label="شروع"><input type="time" value={form.start} onChange={e=>setForm(f=>({...f,start:e.target.value}))} className="crm-input w-full"/></Field><Field label="پایان"><input type="time" value={form.end} onChange={e=>setForm(f=>({...f,end:e.target.value}))} className="crm-input w-full"/></Field><div className="sm:col-span-2"><Field label="یادداشت"><textarea value={form.note} onChange={e=>setForm(f=>({...f,note:e.target.value}))} className="crm-input min-h-20 w-full"/></Field></div></div>{error&&<p className="mt-3 rounded-xl bg-rose-50 p-3 text-xs font-bold text-rose-700">{error}</p>}<div className="mt-5 flex gap-2"><button type="button" onClick={()=>setModal(null)} className="crm-secondary-action flex-1">انصراف</button><button type="button" disabled={saving} onClick={create} className="crm-action flex-1">{saving?"در حال ثبت...":"ثبت نوبت"}</button></div></div></div>}
 {modal==="detail"&&selected&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4"><div className="w-full max-w-lg rounded-3xl bg-white p-5 shadow-2xl"><div className="flex items-start justify-between"><div><h2 className="text-lg font-black">جزئیات نوبت</h2><p className="mt-1 text-xs text-slate-400">{faDate.format(new Date(selected.startAt))}</p></div><button type="button" onClick={()=>setModal(null)}>✕</button></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-slate-50 p-3"><span className="text-[10px] text-slate-400">مشتری</span><b className="mt-1 block">{customerName(customerMap.get(selected.customerId))}</b></div><div className="rounded-2xl bg-slate-50 p-3"><span className="text-[10px] text-slate-400">وضعیت</span><b className={`mt-1 inline-block rounded-full border px-2 py-1 text-[10px] ${statusClass(selected.status)}`}>{statusLabel(selected.status)}</b></div>{selected.services.map(s=><div key={s.id} className="rounded-2xl bg-slate-50 p-3 sm:col-span-2"><div className="flex items-center justify-between"><b>{s.serviceTitle}</b><span className="text-xs text-slate-500">{staffName(staffMap.get(s.staffId))}</span></div><div className="mt-1 text-[11px] text-slate-400">{timeOf(selected.startAt)} تا {timeOf(selected.endAt)} · {faNumber.format(s.price)} تومان</div></div>)}{selected.note&&<div className="rounded-2xl bg-slate-50 p-3 text-xs sm:col-span-2"><span className="font-bold">یادداشت:</span> {selected.note}</div>}</div>{error&&<p className="mt-3 rounded-xl bg-rose-50 p-3 text-xs font-bold text-rose-700">{error}</p>}<div className="mt-5 flex flex-wrap gap-2">{selected.status===0&&<button type="button" disabled={saving} onClick={()=>action("confirm")} className="crm-action flex-1">{saving?"در حال انجام...":"✓ تأیید نوبت"}</button>}{selected.status!==3&&selected.status!==2&&<button type="button" disabled={saving} onClick={()=>action("cancel")} className="crm-secondary-action flex-1 text-rose-600">لغو نوبت</button>}<button type="button" onClick={()=>setModal(null)} className="crm-secondary-action flex-1">بستن</button></div></div></div>}
 </div></main>
}
