"use client";

import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { apiFetch, getCustomers, getServices, getStaff, type Customer, type Service, type Staff, type PagedResult } from "@/lib/api";
import { useAuth } from "@/components/auth-provider";
import { PersianDatePicker, PersianDateTimePicker } from "@/components/persian-date-picker";

type VisitService = { id: string; serviceId: string; staffId: string; serviceTitle: string; price: number; durationMinutes: number; suggestedReturnDays: number | null; staffName: string; staffMobile: string | null };
type Visit = { id: string; businessId: string; customerId: string; customerName: string; customerMobile: string | null; appointmentId: string | null; visitAt: string; totalAmount: number | null; note: string | null; createdAt: string; updatedAt: string | null; services: VisitService[] };

const dateTime = (v: string) => new Intl.DateTimeFormat("fa-IR", { year: "numeric", month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" }).format(new Date(v));
const nameOf = (c: Customer) => [c.firstName, c.lastName].filter(Boolean).join(" ");
const staffName = (s: Staff) => [s.firstName, s.lastName].filter(Boolean).join(" ");
function Loading() { return <div className="space-y-2">{[1,2,3,4,5].map(x => <div key={x} className="h-24 animate-pulse rounded-2xl bg-white/70" />)}</div>; }
function Badge({ children }: { children: React.ReactNode }) { return <span className="rounded-full bg-pink-50 px-2.5 py-1 text-[10px] font-black text-pink-700">{children}</span>; }

export default function VisitsPage() {
  const { auth, businessId, isReady } = useAuth();
  const activeBusinessId = businessId ?? auth?.businesses[0]?.id ?? null;
  const qc = useQueryClient();
  const [page, setPage] = useState(1), [from, setFrom] = useState(""), [to, setTo] = useState("");
  const [selected, setSelected] = useState<Visit | null>(null), [openCreate, setOpenCreate] = useState(false);
  const [customerId, setCustomerId] = useState(""), [serviceId, setServiceId] = useState(""), [staffId, setStaffId] = useState("");
  const [visitAt, setVisitAt] = useState(""), [amount, setAmount] = useState(""), [note, setNote] = useState("");
  const [error, setError] = useState(""), [saving, setSaving] = useState(false);

  const visits = useQuery({ queryKey: ["visits", activeBusinessId, page, from, to], queryFn: () => { const p = new URLSearchParams({ page: String(page), pageSize: "12" }); if (from) p.set("from", `${from}T00:00:00`); if (to) p.set("to", `${to}T23:59:59`); return apiFetch<PagedResult<Visit>>(`/api/businesses/${activeBusinessId}/visits?${p}`); }, enabled: isReady && !!activeBusinessId, staleTime: 15_000 });
  const customers = useQuery({ queryKey: ["visit-customers", activeBusinessId], queryFn: () => getCustomers(activeBusinessId!, 1, 100, "", true), enabled: openCreate && !!activeBusinessId });
  const services = useQuery({ queryKey: ["visit-services", activeBusinessId], queryFn: () => getServices(activeBusinessId!, 1, 100, "", true), enabled: openCreate && !!activeBusinessId });
  const staff = useQuery({ queryKey: ["visit-staff", activeBusinessId], queryFn: () => getStaff(activeBusinessId!, 1, 100, "", true), enabled: openCreate && !!activeBusinessId });

  if (!isReady || !activeBusinessId) return <main className="p-4"><Loading /></main>;
  const data = visits.data;
  const resetCreate = () => { setCustomerId(""); setServiceId(""); setStaffId(""); setVisitAt(""); setAmount(""); setNote(""); setError(""); setOpenCreate(false); };
  async function submit(e: React.FormEvent) {
    e.preventDefault(); setError("");
    if (!customerId || !serviceId || !staffId) return setError("مشتری، خدمت و ارائه‌دهنده خدمت را انتخاب کنید.");
    if (!visitAt) return setError("تاریخ و ساعت مراجعه الزامی است.");
    const totalAmount = amount.trim() ? Number(amount) : undefined;
    if (totalAmount !== undefined && (!Number.isFinite(totalAmount) || totalAmount < 0)) return setError("مبلغ باید عددی صفر یا بیشتر باشد.");
    setSaving(true);
    try { await apiFetch<Visit>(`/api/businesses/${activeBusinessId}/visits`, { method: "POST", body: JSON.stringify({ customerId, visitAt: new Date(visitAt).toISOString(), totalAmount, note: note.trim() || undefined, services: [{ serviceId, staffId }] }) }); resetCreate(); await qc.invalidateQueries({ queryKey: ["visits", activeBusinessId] }); }
    catch (err) { setError(err instanceof Error ? err.message : "ثبت مراجعه انجام نشد."); } finally { setSaving(false); }
  }

  return <main className="-mx-4 -mt-5 min-h-[calc(100vh-65px)] bg-gradient-to-b from-rose-50 via-pink-50/60 to-violet-50/40 px-4 pb-10 pt-5 sm:-mx-8 sm:-mt-8 sm:px-8 sm:pt-7">
    <div className="mx-auto max-w-7xl">
      <header className="mb-5 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[11px] font-bold text-pink-600">سوابق واقعی دریافت خدمت</p><h1 className="mt-1 text-2xl font-black tracking-tight text-slate-950 sm:text-3xl">مراجعه‌ها</h1><p className="mt-1 text-xs leading-5 text-slate-500 sm:text-sm">سوابق واقعی مشتری، خدمات دریافت‌شده و ارائه‌دهندگان خدمت.</p></div><button type="button" onClick={() => { setError(""); setOpenCreate(true); }} className="crm-action self-start !min-h-10 !rounded-xl !px-4 !py-2.5 !text-xs bg-gradient-to-l from-pink-500 to-rose-500 shadow-md shadow-pink-200 sm:self-auto sm:!text-sm">＋ ثبت مراجعه</button></header>
      <section className="crm-card mb-4 p-3.5 sm:p-4"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-[1fr_1fr_auto]"><label><span className="mb-1.5 block text-[11px] font-bold text-slate-600">از تاریخ</span><PersianDatePicker value={from} onChange={value => { setFrom(value); setPage(1); }} /></label><label><span className="mb-1.5 block text-[11px] font-bold text-slate-600">تا تاریخ</span><PersianDatePicker value={to} onChange={value => { setTo(value); setPage(1); }} /></label><button type="button" onClick={() => { setFrom(""); setTo(""); setPage(1); }} className="crm-secondary-action self-end !min-h-11">حذف فیلتر</button></div></section>
      {visits.isLoading ? <Loading /> : visits.isError ? <section className="crm-card p-8 text-center"><h2 className="font-black text-slate-900">بارگذاری مراجعه‌ها انجام نشد</h2><button onClick={() => visits.refetch()} className="crm-secondary-action mt-4">تلاش مجدد</button></section> : !data?.items.length ? <section className="crm-card p-10 text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-pink-50 text-pink-500">✓</div><h2 className="mt-4 text-lg font-black text-slate-900">مراجعه‌ای ثبت نشده است</h2><p className="mt-1 text-sm text-slate-500">برای مراجعه بدون نوبت می‌توانید یک رکورد جدید ثبت کنید.</p></section> : <>
        <section className="hidden overflow-hidden rounded-3xl border border-white/80 bg-white/95 shadow-sm md:block"><div className="grid grid-cols-[1.2fr_1fr_1.35fr_1fr_130px] gap-4 border-b border-slate-100 px-6 py-3 text-[11px] font-black text-slate-400"><span>مشتری</span><span>زمان مراجعه</span><span>خدمات</span><span>ارائه‌دهنده</span><span>مبلغ</span></div>{data.items.map(v => <button key={v.id} onClick={() => setSelected(v)} className="grid w-full grid-cols-[1.2fr_1fr_1.35fr_1fr_130px] items-center gap-4 border-b border-slate-100 px-6 py-4 text-right last:border-0 hover:bg-pink-50/40"><span className="min-w-0"><strong className="block truncate text-sm font-black text-slate-800">{v.customerName || "مشتری بدون نام"}</strong>{v.customerMobile && <small className="mt-1 block text-[10px] text-slate-400">{v.customerMobile}</small>}</span><span className="text-xs text-slate-500">{dateTime(v.visitAt)}</span><span className="flex flex-wrap gap-1.5">{v.services.map(s => <Badge key={s.id}>{s.serviceTitle}</Badge>)}</span><span className="min-w-0 text-xs text-slate-600">{v.services.map(s => s.staffName).filter(Boolean).filter((x, i, a) => a.indexOf(x) === i).join("، ") || "—"}</span><span className="text-xs font-black text-slate-700">{v.totalAmount == null ? "—" : `${v.totalAmount.toLocaleString("fa-IR")} تومان`}</span></button>)}</section>
        <section className="space-y-2 md:hidden">{data.items.map(v => <button key={v.id} onClick={() => setSelected(v)} className="w-full rounded-2xl border border-white/80 bg-white/95 p-4 text-right shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-black text-slate-800">{v.customerName || "مشتری بدون نام"}</p><p className="mt-1 text-[11px] text-slate-500">{v.customerMobile || "شماره ثبت نشده"}</p><p className="mt-1 text-[11px] text-slate-400">{dateTime(v.visitAt)}</p></div><span className="text-xs font-black text-slate-700">{v.totalAmount == null ? "—" : `${v.totalAmount.toLocaleString("fa-IR")} تومان`}</span></div><div className="mt-3 flex flex-wrap gap-1.5">{v.services.map(s => <Badge key={s.id}>{s.serviceTitle} · {s.staffName}</Badge>)}</div></button>)}</section>
        <div className="mt-4 flex items-center justify-between rounded-2xl border border-white/80 bg-white/80 px-3 py-2.5 text-[11px] font-bold text-slate-500"><span>{data.totalCount.toLocaleString("fa-IR")} مراجعه</span><div className="flex items-center gap-1.5"><button disabled={data.page <= 1} onClick={() => setPage(p => p - 1)} className="rounded-lg border border-slate-200 bg-white px-3 py-1.5 disabled:opacity-40">قبلی</button><span>{data.page.toLocaleString("fa-IR")} / {data.totalPages.toLocaleString("fa-IR")}</span><button disabled={data.page >= data.totalPages} onClick={() => setPage(p => p + 1)} className="rounded-lg border border-slate-200 bg-white px-3 py-1.5 disabled:opacity-40">بعدی</button></div></div>
      </>}
    </div>

    {selected && <div className="fixed inset-0 z-50 flex items-end justify-center bg-slate-950/35 p-0 backdrop-blur-[3px] sm:items-center sm:p-4" onMouseDown={() => setSelected(null)}><div role="dialog" aria-modal="true" className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-t-[28px] bg-white shadow-2xl sm:rounded-[28px]" onMouseDown={e => e.stopPropagation()}><div className="border-b border-slate-100 bg-gradient-to-l from-pink-50 to-white px-5 py-5"><div className="flex items-start justify-between gap-4"><div><p className="text-[11px] font-bold text-pink-600">جزئیات مراجعه</p><h2 className="mt-1 text-xl font-black text-slate-950">{selected.customerName || "مشتری بدون نام"}</h2><p className="mt-1 text-xs text-slate-500">{selected.customerMobile || "شماره ثبت نشده"} · {dateTime(selected.visitAt)}</p></div><button onClick={() => setSelected(null)} className="h-10 w-10 rounded-xl border border-slate-200 text-lg text-slate-500">×</button></div></div><div className="space-y-4 p-5"><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-slate-50 p-4"><p className="text-[10px] text-slate-400">نوع مراجعه</p><p className="mt-1 text-sm font-black text-slate-800">{selected.appointmentId ? "تکمیل‌شده از نوبت" : "مراجعه مستقیم"}</p></div><div className="rounded-2xl bg-slate-50 p-4"><p className="text-[10px] text-slate-400">شناسه مراجعه</p><p className="mt-1 break-all text-[10px] font-bold text-slate-600">{selected.id}</p></div></div><div><p className="mb-2 text-xs font-black text-slate-700">خدمات و ارائه‌دهنده</p><div className="space-y-2">{selected.services.map(s => <div key={s.id} className="rounded-xl border border-slate-100 p-3"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black text-slate-800">{s.serviceTitle}</p><p className="mt-1 text-[10px] text-slate-400">{s.durationMinutes.toLocaleString("fa-IR")} دقیقه · بازگشت پیشنهادی {s.suggestedReturnDays == null ? "—" : `${s.suggestedReturnDays.toLocaleString("fa-IR")} روز`}</p></div><span className="text-xs font-bold text-slate-700">{s.price.toLocaleString("fa-IR")} تومان</span></div><div className="mt-2 border-t border-slate-100 pt-2 text-[11px] font-bold text-slate-600">ارائه‌دهنده: {s.staffName || "ثبت نشده"}{s.staffMobile ? ` · ${s.staffMobile}` : ""}</div></div>)}</div></div>{selected.note && <div className="rounded-xl bg-slate-50 p-3 text-xs leading-6 text-slate-600">{selected.note}</div>}<div className="flex justify-between border-t border-slate-100 pt-4 text-sm"><span className="text-slate-400">مبلغ کل</span><b>{selected.totalAmount == null ? "—" : `${selected.totalAmount.toLocaleString("fa-IR")} تومان`}</b></div></div></div></div>}

    {openCreate && <div className="fixed inset-0 z-50 flex items-end justify-center bg-slate-950/35 p-0 backdrop-blur-[3px] sm:items-center sm:p-4" onMouseDown={() => !saving && resetCreate()}><form onSubmit={submit} role="dialog" aria-modal="true" className="max-h-[92vh] w-full max-w-lg overflow-y-auto rounded-t-[28px] bg-white shadow-2xl sm:rounded-[28px]" onMouseDown={e => e.stopPropagation()}><div className="border-b border-slate-100 bg-gradient-to-l from-pink-50 to-white px-5 py-5"><div className="flex items-start justify-between"><div><p className="text-[11px] font-bold text-pink-600">مراجعه جدید</p><h2 className="mt-1 text-xl font-black">ثبت مراجعه مستقیم</h2></div><button type="button" onClick={resetCreate} className="h-10 w-10 rounded-xl border border-slate-200 text-lg text-slate-500">×</button></div></div><div className="space-y-4 p-5"><label><span className="mb-1.5 block text-xs font-bold text-slate-700">مشتری *</span><select value={customerId} onChange={e => setCustomerId(e.target.value)} className="crm-input w-full"><option value="">انتخاب مشتری</option>{customers.data?.items.map(c => <option key={c.id} value={c.id}>{nameOf(c)} · {c.mobile}</option>)}</select></label><label><span className="mb-1.5 block text-xs font-bold text-slate-700">خدمت *</span><select value={serviceId} onChange={e => setServiceId(e.target.value)} className="crm-input w-full"><option value="">انتخاب خدمت</option>{services.data?.items.map(s => <option key={s.id} value={s.id}>{s.title}</option>)}</select></label><label><span className="mb-1.5 block text-xs font-bold text-slate-700">ارائه‌دهنده خدمت *</span><select value={staffId} onChange={e => setStaffId(e.target.value)} className="crm-input w-full"><option value="">انتخاب ارائه‌دهنده</option>{staff.data?.items.map(s => <option key={s.id} value={s.id}>{staffName(s)}{s.mobile ? ` · ${s.mobile}` : ""}</option>)}</select></label><label><span className="mb-1.5 block text-xs font-bold text-slate-700">تاریخ و ساعت مراجعه *</span><input type="datetime-local" value={visitAt} onChange={e => setVisitAt(e.target.value)} className="crm-input w-full" /></label><label><span className="mb-1.5 block text-xs font-bold text-slate-700">مبلغ</span><input inputMode="decimal" value={amount} onChange={e => setAmount(e.target.value)} className="crm-input w-full" placeholder="اختیاری" /></label><label><span className="mb-1.5 block text-xs font-bold text-slate-700">یادداشت</span><textarea value={note} onChange={e => setNote(e.target.value)} rows={3} className="crm-input w-full" placeholder="اختیاری" /></label>{error && <div className="rounded-xl bg-rose-50 p-3 text-xs font-bold text-rose-700">{error}</div>}<button disabled={saving} className="crm-action w-full !min-h-11 disabled:opacity-50">{saving ? "در حال ثبت..." : "ثبت مراجعه"}</button></div></form></div>}
  </main>;
}
