"use client";

import { FormEvent, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { cancelReminder, completeReminder, createReminder, getCustomers, getReminders, getServices } from "../../lib/api";
import { useAuth } from "../../components/auth-provider";
import { PersianDateTimePicker, PersianDatePicker } from "../../components/persian-date-picker";
import { CustomerPicker } from "../../components/customer-picker";

function formatDate(value: string) { return new Intl.DateTimeFormat("fa-IR", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }
function statusLabel(status: number) { if (status === 1) return "انجام‌شده"; if (status === 2) return "لغوشده"; return "باز"; }
function notes(value: string | null) { return (value ?? "").split("\n").filter(line => !line.startsWith("نتیجه اقدام:")).join("\n").trim(); }
function resultNote(value: string | null) { return (value ?? "").split("\n").find(line => line.startsWith("نتیجه اقدام:"))?.replace("نتیجه اقدام:", "").trim() ?? ""; }

export default function FollowUpsPage() {
  const { businessId: activeBusinessId } = useAuth();
  const queryClient = useQueryClient();
  const [status, setStatus] = useState<number | null>(0); const [page, setPage] = useState(1);
  const [from, setFrom] = useState(""); const [to, setTo] = useState("");
  const [openCreate, setOpenCreate] = useState(false); const [completionItem, setCompletionItem] = useState<any | null>(null); const [completionNote, setCompletionNote] = useState("");
  const [customerId, setCustomerId] = useState(""); const [serviceId, setServiceId] = useState(""); const [title, setTitle] = useState(""); const [dueAt, setDueAt] = useState(""); const [note, setNote] = useState("");

  const reminders = useQuery({ queryKey: ["reminders", activeBusinessId, status, page, from, to], queryFn: () => getReminders(activeBusinessId!, status, page, 20, from, to), enabled: !!activeBusinessId });
  const customers = useQuery({ queryKey: ["reminder-customers", activeBusinessId], queryFn: () => getCustomers(activeBusinessId!, 1, 100, "", true), enabled: !!activeBusinessId && openCreate });
  const services = useQuery({ queryKey: ["reminder-services", activeBusinessId], queryFn: () => getServices(activeBusinessId!, 1, 100, "", true), enabled: !!activeBusinessId && openCreate });

  const create = useMutation({ mutationFn: () => createReminder(activeBusinessId!, { customerId, serviceId: serviceId || undefined, title, dueAt: new Date(dueAt).toISOString(), note: note || undefined }), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["reminders", activeBusinessId] }); setOpenCreate(false); setCustomerId(""); setServiceId(""); setTitle(""); setDueAt(""); setNote(""); } });
  const complete = useMutation({ mutationFn: () => completeReminder(activeBusinessId!, completionItem.id, completionNote), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["reminders", activeBusinessId] }); setCompletionItem(null); setCompletionNote(""); } });
  const cancel = useMutation({ mutationFn: (id: string) => cancelReminder(activeBusinessId!, id), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["reminders", activeBusinessId] }) });

  function submit(event: FormEvent) { event.preventDefault(); if (!customerId || !title.trim() || !dueAt) return; create.mutate(); }
  function openCompletion(item: any) { setCompletionItem(item); setCompletionNote(""); }

  return <main className="space-y-6">
    <header className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-2xl font-bold text-slate-900">پیگیری‌ها</h1><p className="mt-1 text-sm text-slate-500">اقدام‌های دستی برای پیگیری مشتریان</p></div><button onClick={() => setOpenCreate(true)} className="rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white">+ پیگیری جدید</button></header>
    <div className="space-y-3 rounded-2xl border border-slate-200 bg-white p-3">
      <div className="flex gap-2 overflow-x-auto">{[[null,"همه"],[0,"باز"],[1,"انجام‌شده"],[2,"لغوشده"]].map(([value,label]) => <button key={String(value)} onClick={() => { setStatus(value as number | null); setPage(1); }} className={`whitespace-nowrap rounded-xl px-4 py-2 text-sm font-medium ${status === value ? "bg-slate-900 text-white" : "text-slate-600 hover:bg-slate-100"}`}>{label}</button>)}</div>
      <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-[1fr_1fr_auto_auto]"><label><span className="mb-1 block text-[11px] font-bold text-slate-600">از تاریخ</span><PersianDatePicker value={from} onChange={v => { setFrom(v); setPage(1); }} /></label><label><span className="mb-1 block text-[11px] font-bold text-slate-600">تا تاریخ</span><PersianDatePicker value={to} onChange={v => { setTo(v); setPage(1); }} /></label><button type="button" onClick={() => { const d = new Date(); const v = `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`; setFrom(v); setTo(v); setPage(1); }} className="crm-secondary-action self-end">امروز</button><button type="button" onClick={() => { setFrom(""); setTo(""); setPage(1); }} className="crm-secondary-action self-end">همه تاریخ‌ها</button></div>
    </div>
    {reminders.isLoading && <div className="rounded-2xl border border-slate-200 bg-white p-10 text-center text-slate-500">در حال دریافت پیگیری‌ها...</div>}
    {reminders.isError && <div className="rounded-2xl border border-red-200 bg-red-50 p-5 text-sm text-red-700">دریافت پیگیری‌ها با خطا مواجه شد.</div>}
    {reminders.data && reminders.data.items.length === 0 && <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-12 text-center"><p className="font-semibold text-slate-700">پیگیری‌ای برای نمایش وجود ندارد.</p><p className="mt-1 text-sm text-slate-500">از Smart List یا دکمه بالا یک پیگیری ثبت کنید.</p></div>}
    {reminders.data && reminders.data.items.length > 0 && <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white">
      <div className="hidden overflow-x-auto md:block"><table className="w-full text-right text-sm"><thead className="bg-slate-50 text-slate-500"><tr><th className="px-5 py-3">مشتری</th><th className="px-5 py-3">عنوان</th><th className="px-5 py-3">موعد</th><th className="px-5 py-3">خدمت</th><th className="px-5 py-3">وضعیت</th><th className="px-5 py-3">عملیات</th></tr></thead><tbody className="divide-y divide-slate-100">{reminders.data.items.map(item => { const initialNote = notes(item.note); const outcome = resultNote(item.note); return <tr key={item.id}><td className="px-5 py-4 font-medium text-slate-800"><div>{item.customerName || "مشتری بدون نام"}</div><div className="mt-1 text-[10px] font-normal text-slate-400" dir="ltr">{item.customerMobile || ""}</div></td><td className="px-5 py-4 text-slate-700"><div>{item.title}</div>{initialNote && <p className="mt-1 max-w-sm whitespace-pre-line text-[11px] leading-5 text-slate-400">{initialNote}</p>}{outcome && <div className="mt-2 max-w-sm rounded-lg bg-emerald-50 px-2.5 py-2 text-[11px] leading-5 text-emerald-700"><span className="font-black">نتیجه:</span> {outcome}</div>}</td><td className="px-5 py-4 text-slate-600">{formatDate(item.dueAt)}</td><td className="px-5 py-4 text-slate-600">{item.serviceTitle || "—"}</td><td className="px-5 py-4"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs">{statusLabel(item.status)}</span></td><td className="px-5 py-4">{item.status === 0 && <div className="flex gap-2"><button onClick={() => openCompletion(item)} className="rounded-lg bg-emerald-50 px-3 py-1.5 text-xs font-semibold text-emerald-700">انجام شد</button><button onClick={() => cancel.mutate(item.id)} className="rounded-lg bg-red-50 px-3 py-1.5 text-xs font-semibold text-red-700">لغو</button></div>}</td></tr>; })}</tbody></table></div>
      <div className="divide-y divide-slate-100 md:hidden">{reminders.data.items.map(item => { const initialNote = notes(item.note); const outcome = resultNote(item.note); return <article key={item.id} className="p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold text-slate-800">{item.title}</h3><p className="mt-1 text-sm text-slate-700">{item.customerName || "مشتری بدون نام"}</p><p className="mt-0.5 text-[10px] text-slate-400" dir="ltr">{item.customerMobile || ""}</p></div><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs">{statusLabel(item.status)}</span></div><p className="mt-3 text-sm text-slate-600">موعد: {formatDate(item.dueAt)}</p>{item.serviceTitle && <p className="mt-1 text-sm text-slate-500">خدمت: {item.serviceTitle}</p>}{initialNote && <p className="mt-3 whitespace-pre-line rounded-xl bg-slate-50 px-3 py-2 text-[11px] leading-5 text-slate-500">{initialNote}</p>}{outcome && <p className="mt-2 whitespace-pre-line rounded-xl bg-emerald-50 px-3 py-2 text-[11px] leading-5 text-emerald-700"><b>نتیجه اقدام:</b> {outcome}</p>}{item.status === 0 && <div className="mt-4 flex gap-2"><button onClick={() => openCompletion(item)} className="flex-1 rounded-lg bg-emerald-50 px-3 py-2 text-xs font-semibold text-emerald-700">انجام شد</button><button onClick={() => cancel.mutate(item.id)} className="flex-1 rounded-lg bg-red-50 px-3 py-2 text-xs font-semibold text-red-700">لغو</button></div>}</article>; })}</div>
      {reminders.data.totalPages > 1 && <div className="flex items-center justify-between border-t border-slate-100 p-4 text-sm"><button disabled={page <= 1} onClick={() => setPage(x => x - 1)} className="rounded-lg border px-3 py-2 disabled:opacity-40">قبلی</button><span>صفحه {page} از {reminders.data.totalPages}</span><button disabled={page >= reminders.data.totalPages} onClick={() => setPage(x => x + 1)} className="rounded-lg border px-3 py-2 disabled:opacity-40">بعدی</button></div>}
    </section>}

    {openCreate && <div className="fixed inset-0 z-50 flex items-end justify-center bg-slate-900/40 p-0 sm:items-center sm:p-4"><form onSubmit={submit} className="w-full max-w-lg space-y-4 rounded-t-3xl bg-white p-5 shadow-xl sm:rounded-3xl"><div className="flex items-center justify-between"><h2 className="text-lg font-bold">پیگیری جدید</h2><button type="button" onClick={() => setOpenCreate(false)} className="text-slate-400">✕</button></div><label className="block text-sm"><span className="mb-1 block font-medium">مشتری</span><CustomerPicker items={customers.data?.items ?? []} value={customerId} onChange={setCustomerId} required /></label><label className="block text-sm"><span className="mb-1 block font-medium">خدمت مرتبط</span><select value={serviceId} onChange={e => setServiceId(e.target.value)} className="w-full rounded-xl border px-3 py-2.5"><option value="">بدون خدمت مشخص</option>{services.data?.items.map(x => <option key={x.id} value={x.id}>{x.title}</option>)}</select></label><label className="block text-sm"><span className="mb-1 block font-medium">عنوان پیگیری</span><input value={title} onChange={e => setTitle(e.target.value)} className="w-full rounded-xl border px-3 py-2.5" placeholder="مثلاً تماس برای یادآوری مراجعه" required /></label><label className="block text-sm"><span className="mb-1 block font-medium">موعد پیگیری</span><PersianDateTimePicker value={dueAt} onChange={setDueAt} /></label><label className="block text-sm"><span className="mb-1 block font-medium">یادداشت اولیه</span><textarea value={note} onChange={e => setNote(e.target.value)} rows={3} className="w-full rounded-xl border px-3 py-2.5" /></label>{create.isError && <p className="text-sm text-red-600">ثبت پیگیری انجام نشد.</p>}<div className="flex gap-2 pt-2"><button type="button" onClick={() => setOpenCreate(false)} className="flex-1 rounded-xl border px-4 py-3 font-semibold">انصراف</button><button disabled={create.isPending} className="flex-1 rounded-xl bg-slate-900 px-4 py-3 font-semibold text-white disabled:opacity-50">{create.isPending ? "در حال ثبت..." : "ثبت پیگیری"}</button></div></form></div>}

    {completionItem && <div className="fixed inset-0 z-50 flex items-end justify-center bg-slate-900/40 p-0 sm:items-center sm:p-4"><form onSubmit={e => { e.preventDefault(); complete.mutate(); }} className="w-full max-w-md space-y-4 rounded-t-3xl bg-white p-5 shadow-xl sm:rounded-3xl"><div><h2 className="text-lg font-black text-slate-900">ثبت نتیجه پیگیری</h2><p className="mt-1 text-xs text-slate-500">{completionItem.title}</p><p className="mt-1 text-xs text-slate-700">{completionItem.customerName || "مشتری بدون نام"}</p></div><label className="block text-sm"><span className="mb-1 block font-medium">توضیحات اقدام</span><textarea autoFocus value={completionNote} onChange={e => setCompletionNote(e.target.value)} rows={4} className="w-full rounded-xl border px-3 py-2.5" placeholder="مثلاً با مشتری تماس گرفته شد و برای شنبه هماهنگ شد." /></label>{complete.isError && <p className="text-xs text-red-600">ثبت نتیجه پیگیری انجام نشد.</p>}<div className="flex gap-2"><button type="button" onClick={() => setCompletionItem(null)} className="flex-1 rounded-xl border px-4 py-3 font-bold">انصراف</button><button disabled={complete.isPending} className="flex-1 rounded-xl bg-emerald-600 px-4 py-3 font-bold text-white disabled:opacity-50">{complete.isPending ? "در حال ثبت..." : "ثبت و تکمیل"}</button></div></form></div>}
  </main>;
}
