"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { getCustomerProfile, updateCustomer } from "@/lib/api";
import { useAuth } from "@/components/auth-provider";
import { PersianDatePicker } from "@/components/persian-date-picker";
import { SmsComposer } from "@/components/sms-composer";

const faDate = (value: string | null) => value ? new Intl.DateTimeFormat("fa-IR", { year: "numeric", month: "long", day: "numeric" }).format(new Date(value)) : "—";
const faDateTime = (value: string) => new Intl.DateTimeFormat("fa-IR", { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" }).format(new Date(value));
const money = (value: number | null) => value == null ? "—" : `${value.toLocaleString("fa-IR")} تومان`;

function Avatar() { return <span className="flex h-16 w-16 shrink-0 items-center justify-center rounded-2xl bg-pink-50 text-pink-500 ring-1 ring-pink-100"><svg viewBox="0 0 48 48" fill="none" className="h-12 w-12" aria-hidden="true"><path d="M8 40c2-7.2 7.4-10.8 16-10.8S38 32.8 40 40" fill="currentColor" opacity=".72"/><path d="M15 23C12.8 14.2 17.2 7 25.1 7c7.6 0 12.5 6.3 9.7 15.8-1.8-2.4-4.2-4.7-7.2-5.6-2.4 2.2-5.7 3.2-9.9 2.7-.8.8-1.6 1.7-2.7 2.6Z" fill="currentColor"/><path d="M17.5 25c1.1 3 3.5 4.7 6.7 4.7 3.5 0 5.9-1.9 6.9-4.7" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" opacity=".45"/></svg></span>; }
function Section({ title, count, children }: { title: string; count?: number; children: React.ReactNode }) { return <section className="crm-card overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 px-4 py-3.5 sm:px-5"><h2 className="text-sm font-black text-slate-900">{title}</h2>{count != null && <span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-black text-slate-500">{count.toLocaleString("fa-IR")}</span>}</div>{children}</section>; }
function ReturnBadge({ days, future }: { days: number; future: boolean }) { if (future) return <span className="rounded-full bg-blue-50 px-2.5 py-1 text-[10px] font-black text-blue-700">نوبت ثبت شده</span>; if (days > 30) return <span className="rounded-full bg-rose-50 px-2.5 py-1 text-[10px] font-black text-rose-700">در معرض ریسک</span>; if (days > 0) return <span className="rounded-full bg-amber-50 px-2.5 py-1 text-[10px] font-black text-amber-700">عقب‌افتاده</span>; return <span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[10px] font-black text-emerald-700">نزدیک موعد</span>; }

type EditForm = { firstName: string; lastName: string; mobile: string; birthDate: string; note: string; isActive: boolean };

export default function CustomerProfilePage() {
  const params = useParams<{ customerId: string }>();
  const { auth, businessId, isReady } = useAuth();
  const activeBusinessId = businessId ?? auth?.businesses[0]?.id ?? null;
  const queryClient = useQueryClient();
  const [editing, setEditing] = useState(false);
  const [smsOpen, setSmsOpen] = useState(false);
  const [form, setForm] = useState<EditForm>({ firstName: "", lastName: "", mobile: "", birthDate: "", note: "", isActive: true });
  const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const profile = useQuery({ queryKey: ["customer-profile", activeBusinessId, params.customerId], queryFn: () => getCustomerProfile(activeBusinessId!, params.customerId), enabled: isReady && !!activeBusinessId && !!params.customerId, staleTime: 15_000 });

  if (!isReady || !activeBusinessId || profile.isLoading) return <main className="p-4"><div className="mx-auto max-w-7xl space-y-3">{[1,2,3].map(x => <div key={x} className="h-28 animate-pulse rounded-3xl bg-white/70" />)}</div></main>;
  if (profile.isError || !profile.data) return <main className="p-4"><section className="crm-card mx-auto max-w-xl p-10 text-center"><h1 className="font-black text-slate-900">اطلاعات مشتری بارگذاری نشد</h1><p className="mt-2 text-sm text-slate-500">لطفاً دوباره تلاش کنید.</p><button onClick={() => profile.refetch()} className="crm-secondary-action mt-4">تلاش مجدد</button></section></main>;

  const { customer, visits, futureAppointments, reminders, returnAnalysis } = profile.data;
  const fullName = [customer.firstName, customer.lastName].filter(Boolean).join(" ");
  const openEdit = () => { setForm({ firstName: customer.firstName, lastName: customer.lastName ?? "", mobile: customer.mobile, birthDate: customer.birthDate ? customer.birthDate.slice(0, 10) : "", note: customer.note ?? "", isActive: customer.isActive }); setError(""); setEditing(true); };
  const save = async (event: React.FormEvent) => { event.preventDefault(); if (!form.firstName.trim() || !form.mobile.trim()) { setError("نام و شماره موبایل الزامی است."); return; } setSaving(true); setError(""); try { await updateCustomer(activeBusinessId!, customer.id, { firstName: form.firstName.trim(), lastName: form.lastName.trim() || undefined, mobile: form.mobile.trim(), birthDate: form.birthDate || undefined, note: form.note.trim() || undefined, isActive: form.isActive }); await queryClient.invalidateQueries({ queryKey: ["customer-profile", activeBusinessId, customer.id] }); setEditing(false); } catch (e) { setError(e instanceof Error ? e.message : "ویرایش مشتری انجام نشد."); } finally { setSaving(false); } };

  return <main className="-mx-4 -mt-5 min-h-[calc(100vh-65px)] bg-gradient-to-b from-rose-50 via-pink-50/60 to-violet-50/40 px-4 pb-10 pt-5 sm:-mx-8 sm:-mt-8 sm:px-8 sm:pt-7">
    <div className="mx-auto max-w-7xl">
      <div className="mb-4 flex items-center gap-2 text-xs font-bold text-slate-500"><Link href="/customers" className="hover:text-pink-600">مشتریان</Link><span>←</span><span className="text-slate-800">پروفایل مشتری</span></div>
      <section className="crm-card mb-4 overflow-hidden"><div className="bg-gradient-to-l from-pink-100/80 via-white to-white px-5 py-5 sm:px-6 sm:py-6"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-4"><Avatar /><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-black tracking-tight text-slate-950">{fullName}</h1><span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${customer.isActive ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-500"}`}>{customer.isActive ? "فعال" : "غیرفعال"}</span></div><p dir="ltr" className="mt-1 text-right text-sm text-slate-500">{customer.mobile}</p><p className="mt-1 text-[11px] text-slate-400">عضویت از {faDate(customer.createdAt)}</p></div></div><div className="flex flex-wrap gap-2"><button onClick={() => setSmsOpen(true)} disabled={!customer.mobile?.trim()} className="crm-action !min-h-10 !rounded-xl !px-4 !py-2.5 !text-xs disabled:cursor-not-allowed disabled:opacity-50">ارسال SMS</button><button onClick={openEdit} className="crm-secondary-action !min-h-10 !rounded-xl !px-4 !py-2.5 !text-xs">ویرایش اطلاعات</button></div></div></div><div className="grid grid-cols-3 border-t border-slate-100 bg-white"><div className="px-3 py-3 text-center"><p className="text-[10px] text-slate-400">تعداد مراجعه</p><p className="mt-1 text-lg font-black text-slate-900">{customer.totalVisits.toLocaleString("fa-IR")}</p></div><div className="border-x border-slate-100 px-3 py-3 text-center"><p className="text-[10px] text-slate-400">آخرین مراجعه</p><p className="mt-1 text-xs font-black text-slate-700">{faDate(customer.lastVisitDate)}</p></div><div className="px-3 py-3 text-center"><p className="text-[10px] text-slate-400">یادآوری باز</p><p className="mt-1 text-lg font-black text-pink-600">{reminders.length.toLocaleString("fa-IR")}</p></div></div></section>
      <div className="grid gap-4 lg:grid-cols-[1.35fr_.65fr]"><div className="space-y-4">
        <Section title="تحلیل بازگشت به تفکیک خدمت" count={returnAnalysis.services.length}>{!returnAnalysis.services.length ? <div className="p-6 text-center text-sm text-slate-500">هنوز سابقه خدمتی برای تحلیل بازگشت ثبت نشده است.</div> : <div className="divide-y divide-slate-100">{returnAnalysis.services.map(item => <div key={item.serviceId} className="px-4 py-4 sm:px-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-black text-slate-900">{item.serviceTitle}</p><p className="mt-1 text-[11px] text-slate-400">آخرین مراجعه: {faDate(item.lastVisitAt)} · چرخه پیشنهادی: {item.suggestedReturnDays.toLocaleString("fa-IR")} روز</p></div><ReturnBadge days={item.daysFromExpectedReturn} future={item.hasFutureAppointment} /></div><div className="mt-3 flex flex-wrap gap-2 text-[11px]"><span className="rounded-xl bg-slate-50 px-3 py-2 text-slate-600">موعد مورد انتظار: <b className="text-slate-800">{faDate(item.expectedReturnDate)}</b></span>{!item.hasFutureAppointment && item.daysFromExpectedReturn > 0 && <span className="rounded-xl bg-rose-50 px-3 py-2 font-bold text-rose-700">{item.daysFromExpectedReturn.toLocaleString("fa-IR")} روز تأخیر</span>}</div></div>)}</div>}</Section>
        <Section title="سوابق مراجعه" count={visits.length}>{!visits.length ? <div className="p-6 text-center text-sm text-slate-500">هنوز مراجعه‌ای ثبت نشده است.</div> : <div className="divide-y divide-slate-100">{visits.map(visit => <div key={visit.id} className="px-4 py-4 sm:px-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black text-slate-800">{faDateTime(visit.visitAt)}</p><div className="mt-2 flex flex-wrap gap-1.5">{visit.services.length ? visit.services.map(service => <span key={service} className="rounded-lg bg-pink-50 px-2 py-1 text-[10px] font-bold text-pink-700">{service}</span>) : <span className="text-[10px] text-slate-400">بدون خدمت ثبت‌شده</span>}</div></div><span className="text-xs font-black text-slate-700">{money(visit.totalAmount)}</span></div>{visit.note && <p className="mt-3 rounded-xl bg-slate-50 px-3 py-2 text-[11px] leading-5 text-slate-500">{visit.note}</p>}</div>)}</div>}</Section>
      </div><div className="space-y-4">
        <Section title="نوبت‌های آینده" count={futureAppointments.length}>{!futureAppointments.length ? <div className="p-6 text-center text-sm text-slate-500">نوبت آینده‌ای ثبت نشده است.</div> : <div className="divide-y divide-slate-100">{futureAppointments.map(item => <div key={item.id} className="px-4 py-4"><div className="flex items-start justify-between gap-2"><div><p className="text-xs font-black text-slate-800">{faDateTime(item.startAt)}</p><p className="mt-1 text-[10px] text-slate-400">تا {new Intl.DateTimeFormat("fa-IR", { hour: "2-digit", minute: "2-digit" }).format(new Date(item.endAt))}</p></div><span className="rounded-full bg-blue-50 px-2 py-1 text-[10px] font-bold text-blue-700">{item.status === "Confirmed" ? "تأیید شده" : item.status === "Completed" ? "تکمیل شده" : "در انتظار"}</span></div><div className="mt-2 flex flex-wrap gap-1.5">{item.services.map(service => <span key={service} className="rounded-lg bg-slate-50 px-2 py-1 text-[10px] font-bold text-slate-600">{service}</span>)}</div></div>)}</div>}</Section>
        <Section title="یادآوری‌ها" count={reminders.length}>{!reminders.length ? <div className="p-6 text-center text-sm text-slate-500">یادآوری بازی وجود ندارد.</div> : <div className="divide-y divide-slate-100">{reminders.map(item => <div key={item.id} className="px-4 py-4"><p className="text-xs font-black text-slate-800">{item.title}</p><p className="mt-1 text-[10px] text-pink-600">سررسید: {faDate(item.dueAt)}</p>{item.note && <p className="mt-2 text-[11px] leading-5 text-slate-500">{item.note}</p>}</div>)}</div>}</Section>
        <Section title="اطلاعات تکمیلی"><div className="space-y-3 px-4 py-4 text-xs"><div className="flex justify-between gap-4"><span className="text-slate-400">تاریخ تولد</span><span className="font-bold text-slate-700">{faDate(customer.birthDate)}</span></div><div className="flex justify-between gap-4"><span className="text-slate-400">آخرین ویرایش</span><span className="font-bold text-slate-700">{faDate(customer.updatedAt)}</span></div>{customer.note && <div className="border-t border-slate-100 pt-3"><p className="mb-1 text-slate-400">یادداشت</p><p className="leading-6 text-slate-600">{customer.note}</p></div>}</div></Section>
      </div></div>
    </div>
    {editing && <div className="fixed inset-0 z-50 flex items-end justify-center bg-slate-950/40 p-0 backdrop-blur-[2px] sm:items-center sm:p-4"><form onSubmit={save} className="w-full max-w-lg space-y-4 rounded-t-3xl bg-white p-5 shadow-2xl sm:rounded-3xl"><div className="flex items-center justify-between"><div><p className="text-[11px] font-bold text-pink-600">اطلاعات مشتری</p><h2 className="mt-1 text-lg font-black">ویرایش مشتری</h2></div><button type="button" onClick={() => !saving && setEditing(false)} className="h-9 w-9 rounded-xl border border-slate-200 text-slate-500">×</button></div><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm"><span className="mb-1 block font-bold">نام</span><input autoFocus value={form.firstName} onChange={e => setForm({...form, firstName:e.target.value})} className="crm-input w-full" /></label><label className="text-sm"><span className="mb-1 block font-bold">نام خانوادگی</span><input value={form.lastName} onChange={e => setForm({...form, lastName:e.target.value})} className="crm-input w-full" /></label></div><label className="block text-sm"><span className="mb-1 block font-bold">شماره موبایل</span><input dir="ltr" inputMode="tel" value={form.mobile} onChange={e => setForm({...form,mobile:e.target.value})} className="crm-input w-full text-right" /></label><label className="block text-sm"><span className="mb-1 block font-bold">تاریخ تولد</span><PersianDatePicker value={form.birthDate} onChange={v => setForm({...form,birthDate:v})} /></label><label className="block text-sm"><span className="mb-1 block font-bold">یادداشت</span><textarea rows={3} value={form.note} onChange={e => setForm({...form,note:e.target.value})} className="crm-input w-full" /></label><label className="flex items-center justify-between rounded-xl bg-slate-50 px-3 py-3 text-xs font-bold"><span>وضعیت مشتری</span><button type="button" onClick={() => setForm({...form,isActive:!form.isActive})} className={`rounded-full px-3 py-1.5 ${form.isActive ? "bg-emerald-100 text-emerald-700" : "bg-slate-200 text-slate-500"}`}>{form.isActive ? "فعال" : "غیرفعال"}</button></label>{error && <p className="rounded-xl bg-rose-50 px-3 py-2 text-xs font-bold leading-5 text-rose-700">{error}</p>}<div className="flex gap-2 border-t border-slate-100 pt-4"><button type="button" disabled={saving} onClick={() => setEditing(false)} className="crm-secondary-action flex-1 !min-h-11">انصراف</button><button disabled={saving} className="crm-action flex-1 !min-h-11">{saving ? "در حال ذخیره..." : "ذخیره تغییرات"}</button></div></form></div>}
    {smsOpen && <SmsComposer businessId={activeBusinessId} customers={[customer]} onClose={() => setSmsOpen(false)} title={`ارسال SMS به ${fullName}`} />}
  </main>;
}
