"use client";

import { useEffect, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { createStaff, getStaff, updateStaff, type Staff } from "@/lib/api";
import { useAuth } from "@/components/auth-provider";

function LoadingRows() { return <div className="space-y-2">{Array.from({ length: 6 }).map((_, i) => <div key={i} className="h-20 animate-pulse rounded-2xl bg-white/70" />)}</div>; }
function Field({ label, required, children }: { label: string; required?: boolean; children: React.ReactNode }) { return <label className="block"><span className="mb-1.5 block text-xs font-bold text-slate-700">{label}{required && <span className="mr-1 text-pink-500">*</span>}</span>{children}</label>; }
function Status({ active }: { active: boolean }) { return active ? <span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[10px] font-black text-emerald-700">فعال</span> : <span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-black text-slate-500">غیرفعال</span>; }
function StaffAvatar() { return <span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-indigo-50 text-indigo-500 ring-2 ring-white"><svg viewBox="0 0 48 48" fill="none" className="h-8 w-8" aria-hidden="true"><circle cx="24" cy="15" r="7" fill="currentColor" opacity=".8"/><path d="M11 40c1.3-7 5.6-10.5 13-10.5S35.7 33 37 40" fill="currentColor" opacity=".65"/></svg></span>; }

type Form = { firstName: string; lastName: string; mobile: string; isActive: boolean };
const emptyForm: Form = { firstName: "", lastName: "", mobile: "", isActive: true };

export default function StaffPage() {
  const { auth, businessId, isReady } = useAuth();
  const activeBusinessId = businessId ?? auth?.businesses[0]?.id ?? null;
  const queryClient = useQueryClient();
  const [searchInput, setSearchInput] = useState(""); const [search, setSearch] = useState("");
  const [status, setStatus] = useState<"active" | "inactive" | "all">("active"); const [page, setPage] = useState(1);
  const [editing, setEditing] = useState<Staff | null>(null); const [open, setOpen] = useState(false); const [form, setForm] = useState<Form>(emptyForm); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { const t = window.setTimeout(() => { setSearch(searchInput.trim()); setPage(1); }, 300); return () => window.clearTimeout(t); }, [searchInput]);
  const isActive = status === "all" ? null : status === "active";
  const query = useQuery({ queryKey: ["staff", activeBusinessId, page, search, status], queryFn: () => getStaff(activeBusinessId!, page, 12, search, isActive), enabled: isReady && !!activeBusinessId, staleTime: 15_000 });
  if (!isReady || !activeBusinessId) return <main className="p-4"><LoadingRows /></main>;
  const data = query.data;
  const openCreate = () => { setEditing(null); setForm(emptyForm); setError(""); setOpen(true); };
  const openEdit = (staff: Staff) => { setEditing(staff); setForm({ firstName: staff.firstName, lastName: staff.lastName, mobile: staff.mobile ?? "", isActive: staff.isActive }); setError(""); setOpen(true); };
  const close = () => { if (!saving) setOpen(false); };
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(""); if (!form.firstName.trim() || !form.lastName.trim()) return setError("نام و نام خانوادگی الزامی است."); setSaving(true); try { if (editing) await updateStaff(activeBusinessId!, editing.id, { firstName: form.firstName.trim(), lastName: form.lastName.trim(), mobile: form.mobile.trim() || undefined, isActive: form.isActive }); else await createStaff(activeBusinessId!, { firstName: form.firstName.trim(), lastName: form.lastName.trim(), mobile: form.mobile.trim() || undefined }); setOpen(false); await queryClient.invalidateQueries({ queryKey: ["staff", activeBusinessId] }); } catch (e) { setError(e instanceof Error ? e.message : "ذخیره کارکنان انجام نشد."); } finally { setSaving(false); } }

  return <main className="-mx-4 -mt-5 min-h-[calc(100vh-65px)] bg-gradient-to-b from-rose-50 via-pink-50/60 to-violet-50/40 px-4 pb-10 pt-5 sm:-mx-8 sm:-mt-8 sm:px-8 sm:pt-7">
    <div className="mx-auto max-w-7xl">
      <header className="mb-5 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[11px] font-bold text-indigo-600">مدیریت تیم</p><h1 className="mt-1 text-2xl font-black tracking-tight text-slate-950 sm:text-3xl">کارکنان</h1><p className="mt-1 text-xs leading-5 text-slate-500 sm:text-sm">اعضای تیم و اطلاعات تماس آن‌ها را مدیریت کنید.</p></div><button onClick={openCreate} className="crm-action self-start !min-h-10 !rounded-xl !px-4 !py-2.5 !text-xs bg-gradient-to-l from-indigo-500 to-violet-500 shadow-md shadow-indigo-200 sm:self-auto sm:!text-sm">＋ کارمند جدید</button></header>
      <section className="crm-card mb-4 p-3.5 sm:p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-center"><label className="relative min-w-0 flex-1"><span className="sr-only">جستجوی کارکنان</span><svg className="pointer-events-none absolute right-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg><input value={searchInput} onChange={e => setSearchInput(e.target.value)} placeholder="جستجو با نام یا شماره موبایل..." className="crm-input w-full !pr-10" /></label><div className="grid grid-cols-3 gap-1 rounded-xl bg-slate-100 p-1 lg:w-[300px]">{([['active','فعال'],['inactive','غیرفعال'],['all','همه']] as const).map(([v,l]) => <button key={v} onClick={() => { setStatus(v); setPage(1); }} aria-pressed={status === v} className={`rounded-lg px-3 py-2 text-[11px] font-bold ${status === v ? "bg-white text-indigo-600 shadow-sm ring-1 ring-slate-200/70" : "text-slate-500"}`}>{l}</button>)}</div></div></section>
      {query.isLoading ? <LoadingRows /> : query.isError ? <section className="crm-card p-8 text-center"><h2 className="font-black">بارگذاری کارکنان انجام نشد</h2><button onClick={() => query.refetch()} className="crm-secondary-action mt-4">تلاش مجدد</button></section> : !data?.items.length ? <section className="crm-card p-10 text-center"><h2 className="text-lg font-black text-slate-900">کارمندی پیدا نشد</h2><p className="mt-1 text-sm text-slate-500">فیلترها را تغییر دهید یا عضو جدیدی ثبت کنید.</p></section> : <>
        <section className="hidden overflow-hidden rounded-3xl border border-white/80 bg-white/95 shadow-sm md:block"><div className="grid grid-cols-[minmax(260px,1.5fr)_180px_120px_110px] items-center gap-4 border-b border-slate-100 px-6 py-3 text-[11px] font-black text-slate-400"><span>کارمند</span><span>موبایل</span><span>وضعیت</span><span></span></div>{data.items.map(s => <button key={s.id} onClick={() => openEdit(s)} className="grid w-full grid-cols-[minmax(260px,1.5fr)_180px_120px_110px] items-center gap-4 border-b border-slate-100 px-6 py-3.5 text-right transition last:border-0 hover:bg-indigo-50/30"><div className="flex items-center gap-3"><StaffAvatar /><div><p className="text-sm font-black text-slate-900">{s.firstName} {s.lastName}</p><p className="mt-0.5 text-[11px] text-slate-400">{s.userId ? "متصل به حساب کاربری" : "کارمند عملیاتی"}</p></div></div><span dir="ltr" className="text-xs text-slate-600">{s.mobile || "بدون شماره"}</span><Status active={s.isActive} /><span className="text-xs font-black text-indigo-500">ویرایش ←</span></button>)}</section>
        <section className="space-y-2 md:hidden">{data.items.map(s => <button key={s.id} onClick={() => openEdit(s)} className="w-full rounded-2xl border border-white/80 bg-white/95 p-4 text-right shadow-sm"><div className="flex items-center gap-3"><StaffAvatar /><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><p className="truncate text-sm font-black text-slate-900">{s.firstName} {s.lastName}</p><Status active={s.isActive} /></div><p dir="ltr" className="mt-1 text-right text-[11px] text-slate-500">{s.mobile || "بدون شماره"}</p></div></div></button>)}</section>
        <div className="mt-4 flex items-center justify-between rounded-2xl border border-white/80 bg-white/80 px-3 py-2.5 text-[11px] font-bold text-slate-500"><span>{data.totalCount.toLocaleString("fa-IR")} کارمند</span><div className="flex items-center gap-1.5"><button disabled={data.page <= 1} onClick={() => setPage(p => p - 1)} className="rounded-lg border border-slate-200 bg-white px-3 py-1.5 disabled:opacity-40">قبلی</button><span className="px-1">{data.page.toLocaleString("fa-IR")} / {data.totalPages.toLocaleString("fa-IR")}</span><button disabled={data.page >= data.totalPages} onClick={() => setPage(p => p + 1)} className="rounded-lg border border-slate-200 bg-white px-3 py-1.5 disabled:opacity-40">بعدی</button></div></div>
      </>}
    </div>
    {open && <div className="fixed inset-0 z-50 flex items-end justify-center bg-slate-950/35 p-0 backdrop-blur-[3px] sm:items-center sm:p-4" onMouseDown={close}><div role="dialog" aria-modal="true" className="w-full max-w-lg rounded-t-[28px] bg-white shadow-2xl sm:rounded-[28px]" onMouseDown={e => e.stopPropagation()}><div className="border-b border-slate-100 bg-gradient-to-l from-indigo-50 to-white px-5 py-4"><div className="flex items-start justify-between"><div><p className="text-[11px] font-bold text-indigo-600">{editing ? "ویرایش کارمند" : "کارمند جدید"}</p><h2 className="mt-1 text-xl font-black">{editing ? `${editing.firstName} ${editing.lastName}` : "ثبت کارمند"}</h2></div><button onClick={close} className="h-10 w-10 rounded-xl border border-slate-200 text-lg text-slate-500">×</button></div></div><form onSubmit={submit} className="space-y-4 px-5 py-5 sm:px-6"><div className="grid gap-4 sm:grid-cols-2"><Field label="نام" required><input autoFocus value={form.firstName} onChange={e => setForm({...form,firstName:e.target.value})} className="crm-input w-full" /></Field><Field label="نام خانوادگی" required><input value={form.lastName} onChange={e => setForm({...form,lastName:e.target.value})} className="crm-input w-full" /></Field></div><Field label="شماره موبایل"><input dir="ltr" inputMode="tel" value={form.mobile} onChange={e => setForm({...form,mobile:e.target.value})} className="crm-input w-full text-right" placeholder="09..." /></Field>{editing && <label className="flex items-center justify-between rounded-xl bg-slate-50 px-3 py-3 text-xs font-bold"><span>وضعیت کارمند</span><button type="button" onClick={() => setForm({...form,isActive:!form.isActive})} className={`rounded-full px-3 py-1.5 ${form.isActive ? "bg-emerald-100 text-emerald-700" : "bg-slate-200 text-slate-500"}`}>{form.isActive ? "فعال" : "غیرفعال"}</button></label>}{error && <p className="rounded-xl bg-rose-50 px-3 py-2 text-xs font-bold leading-5 text-rose-700">{error}</p>}<div className="flex gap-2 border-t border-slate-100 pt-4"><button disabled={saving} className="crm-action flex-1 !min-h-11 !rounded-xl">{saving ? "در حال ذخیره..." : "ذخیره"}</button><button type="button" disabled={saving} onClick={close} className="crm-secondary-action !min-h-11 !rounded-xl">انصراف</button></div></form></div></div>}
  </main>;
}
